export const state = {
    currentUser: null,
    customerCart: [],
    currentPage: 'login',
    adminPage: 'menu',
    firstLoad: true,
    menuItems: [],
    categories: [],
    orders: [],
    users: [],
    salesReport: {
        totalRevenue: 0,
        orderCount: 0,
        bestSeller: null,
        orders: [],
        filterOptions: {
            years: [],
            months: [],
            days: [],
            users: [],
        },
    },
    salesFilter: {
        year: '',
        month: '',
        day: '',
        user: '',
    },
    currentResetToken: null,
    currentResetUsername: null,
    isOrderHistoryOpen: false,
    isCartOpen: false,
};
